### ISSUE TITLE
Not working on Kalidomra SuperClone board

### ISSUE THREAD

**Issue by Robert-Di-Benedetto** [adrianglz64/snappyrom#1] opened 2022-09-28 00:30 UTC
Flashed an AT29C010A-12PC 128KB ROM with Snappy V531 NTSC binary.  Flash was verified to correctly match the binary.  Also examined a dump to manually verify.

Installed in a known good working SuperClone board that has SS V5.22 ROM.  Boots to a black screen.  Tried with both 8K and 32K RAM configurations.  Reinstalled original V5.22 ROM and all is working fine.

Also submitting this issue on the SuperClone GIT area.

**Comment by adrianglz64** [comment] 2022-09-28 03:51
Can you try flashing that AT29C010 with a 128KB ROM made up of two copies of the V5.22 ROM?  It would help to rule out any incompatibility with the flash chip itself.

Just concatenate the V5.22 ROM to itself like:
`copy /b ssv522.bin + ssv522.bin ss522-128k.bin` (windows)
`cat ssv522.bin ssv522.bin >ss522-128k.bin` (mac/unix)

and then flash the resulting 128KB file.  If that doesn't work then it might be a timing issue with the newer parts used in the SuperClone.

**Comment by Robert-Di-Benedetto** [comment] 2022-09-28 04:16
Kalidomra suggested that it was possibly a timing issue as well as the ROM he used for the original SS ROM was 45ns but he hasn't tried your new ROM yet.  
I just tried your suggestion (concatenating two SS v5.22 ROMs) and it was the same failed result - a black screen.  So this is very likely a timing issue.
I have since ordered some faster ROMS: M27C2001-10F1 (256K 100ns), 27C010-70 (128K 70ns) and 27C040-70 (512K 70ns).  When they arrive I will try them out and circle back with the results.

By the way - I also just tried your ROM on an Ultimate II (not II+) and it does start fine but when I try to invoke TMP, it goes to a screen with garbage and then blank.  If I try it by first clearing memory (via the Prepare System for Snapshot), then it doesn't show garbage but it still shows a blank screen.  The original ROM works fine.  Should I open a 2nd issue for this?

**Comment by adrianglz64** [comment] 2022-09-28 04:50
Please let me know if some of those faster chips work and I'll add a note to the readme.  Thanks!

As for the Ultimate, it's being worked on: https://github.com/GideonZ/1541ultimate/issues/288

**Comment by Scyllinice** [comment] 2022-09-28 17:27
I wasn't aware this ROM was intended to work with the SuperClone, so I just updated my build's `W27C020-70Z` with the most recent SnappyROM version and it worked just fine.

**Comment by Robert-Di-Benedetto** [comment] 2022-09-28 17:50
I've just ordered a W27C020-70Z as well.  I'll double confirm when it arrives.  It will be good to have a list of multiple eprom options so sourcing can be easier.

**Comment by Robert-Di-Benedetto** [comment] 2022-10-02 15:44
So far I have confirmed the following:
M27C2001-10F1 does NOT work
AM27HB010-70DC (128k) DOES work
AM27C040-70DC (512k) DOES work

Still waiting on delivery of W27C020-70Z

**Comment by adrianglz64** [comment] 2022-10-03 18:18
Thank you for the update.  It does look like the SuperClone likes faster ROM chips as suggested by Kalidomra.

I wrote a small ROM testing tool for testing 128KB support in the KungFuFlash, but it may come in useful for this too.  I plan on creating a repo for it, but in the meantime you can get it here:
[ssv5romtool.zip
](https://github.com/KimJorgensen/KungFuFlash/files/9662690/ssv5romtool.zip)

It reads each 16K bank of ROM and compares it several times, reporting any mismatches.

**Comment by Robert-Di-Benedetto** [comment] 2022-10-08 21:48
I have now double-confirmed that W27C020-70Z also works.  So we now have 3 confirmed working ROMs.

**Comment by Kalidomra** [comment] 2023-01-27 15:02
I can confirm it works on the SuperClone. I used a W27C010-70 and a 32 pin socket. This can be closed.

**Comment by adrianglz64** [comment] 2023-02-01 22:24
Thank you for taking the time to test.  Closing this.

**Closed by adrianglz64** 2023-02-01 22:24 UTC
